In [1]:
#sum and average 
a=int(input("enter marks"))
b=int(input("enter marks"))
c=int(input("enter marks"))
d=int(input("enter marks"))
e=int(input("enter marks"))
sum=a+b+c+d+e
average=a+b+c+d+e/5
print(sum)
print(average)

enter marks56
enter marks45
enter marks48
enter marks78
enter marks49
276
236.8


In [11]:
#sum of natural number
a=int(input("enter a number"))
sum=0
for i in range(1,a+1):
    sum=sum+i
print(sum)

enter a number10
55


In [16]:
#factoriyal
a=int(input("enter a number"))
fact=1
for i in range(1,a+1):
    fact=fact*i
print(fact)


enter a number3
6


In [5]:
#while loop
i=1
while(i<=10):
    print(i)
    i=i+1
    


1
2
3
4
5
6
7
8
9
10


In [6]:
i=10
while (i!=0):
    print(i)
    i=i-1

10
9
8
7
6
5
4
3
2
1


In [3]:
n=int(input("enter a number"))
i=int(input("enter table till"))
j=1
while (j<=i):
    print(n*j)
    j=j+1
    
    
    
    
    
    

enter a number2
enter table till10
2
4
6
8
10
12
14
16
18
20


In [6]:
def add():
    a=5
    b=6
    c=a+b
    print(c)
add()

11


In [10]:
def sub():
    a=int(input("enter a number"))
    b=int(input("enter a number"))
    c=a-b
    print(c)
sub()

enter a number6
enter a number9
-3


In [11]:
def add(a,b):
    print(a+b)
add(5,3)

8


In [14]:
c=int(input("enter a number "))
d=int(input("enter a number "))
def add(a,b):
    print(a+b)
add(c,d)

enter a number 5
enter a number 65
70


In [19]:
def sum(a,b):
    a=5
    b=6
    print(a+b)
def add(a,b):
    a=6
    b=3
    print(a-b)
def disp():
    sum(a,b)
    add(a,b)

disp()

11
3


In [7]:
r=int(input("enter radius of circle"))
area=(22//7)*(r)**2
circum=2*(22/7)*r
print(area)
print(circum)

enter radius of circle7
147
44.0


In [3]:
c=float(input("temperature of today "))
f=c*(9/5)+32
print(f)

temperature of today 50
122.0


In [18]:
p=int(input("enter principal amount "))
r=float(input("enter rate of intrest "))
t=int(input("enter time for intrest "))
s=(p*r*t)/100
print(s)


enter principal amount 2000
enter rate of intrest 5
enter time for intrest 2
200.0


In [19]:
p=int(input("enter principal amount "))
r=float(input("enter rate of intrest "))
t=int(input("enter time for intrest "))
s=p*((1+r/100)**t)-p
print(s)

enter principal amount 2000
enter rate of intrest 5
enter time for intrest 2
205.0


In [2]:
a=float(input("enter first no."))
b=float(input("enter second no."))
c=float(input("enter third no."))
d=float(input("enter fourth no."))
if (a>b and a>c and a>d):
    print("greatest number is :" , a)
elif (b>c and b>d):
    print("greatest numbe is :", b)
elif(c>d):
    print("greatest number is :", c)
elif(d>c):
    print("greatest number is :", d)
else:
    print("either all value is equal")


enter first no.98
enter second no.56
enter third no.45
enter fourth no.23
greatest number is : 98.0


In [4]:
y=int(input("enter your age "))
if (y>5 and y<12):
    print("kid")
elif (y>=12 and y<18):
    print("teenager")
elif (y>=18 and y<25):
    print("younger")
elif (y>=25 and y<35):
    print("mature")
elif (y>=35 and y<50):
    print("old")
else:
    print("senior citizen")

enter your age 26
mature


In [6]:
n=int(input("enter limit "))
s=0
for i in range(1,n):
    s=i+s
print("the sum is",s)

enter limit 12
the sum is 66


In [7]:
a=int(input("enter a number"))
factorial=1
if a<0:
    print("sorry factorial does not exit for negative number")
elif a==0:
    print("factorial of 0 is 1")
else:
    for i in range(1,a+1):
        factorial=factorial*i
    print("the factorial of",a,"is",factorial)

enter a number5
the factorial of 5 is 120


In [11]:
a=int(input("enter a multiplication number"))
i=0
for i in range(1,11):
    i=a*i
    print(i)

enter a multiplication number2
2
4
6
8
10
12
14
16
18
20


In [4]:
n=int(input("enter the number "))
for i in range(n):
    for j in range (i+1):
        print("*",end=" ")
    print()

enter the number 5
* 
* * 
* * * 
* * * * 
* * * * * 


In [5]:
n=int(input("enter the number "))
for i in range(n,0,-1):
    for j in range (0,i):
        print("*",end=" ")
    print()

enter the number 5
* * * * * 
* * * * 
* * * 
* * 
* 


In [1]:
#1
n= int(input("enter a number"))
for i in range(1,n):
    print(i)

enter a number10
1
2
3
4
5
6
7
8
9


In [6]:
#2
l=[]
n = int(input("enter number of list to start"))
for i in range (0,n):
    l.append(i)
print(l)


enter number of list to start20
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [8]:
#3
l=[1,2,3,4,5,6]
a=l[0],l[5]=l[5],l[0]
print(l)

[6, 2, 3, 4, 5, 1]


In [10]:
#4
a=int(input("enter a number"))
b=int(input("enter a number"))
if a==b:
    print(a ,"=", b)
else:
    print(a, "!=", b )

enter a number10
enter a number20
10 != 20


In [8]:
#5
a=56
b=65
c=45
if a>b and a>c:
    print(a," a is largest value")
elif b>c:
    print(b," b is largest value")
else:
    print(c," c is largest value")

65  b is largest value


In [18]:
#6
year=int(input("enter year "))
if year%4==0 and (year%400==0 or year%100!=0):
    print("congrats it's a leap year")
else:
    print("it's not a leap year")

enter year 2020
congrats it's a leap year


In [2]:
#7
a=int(input("enter first student marks"))
b=int(input("enter second student marks"))
c=int(input("enter third student marks"))
d=int(input("enter fourth student marks"))
e=int(input("enter fivth student marks"))
p=(a+b+c+d+e)/5
print(p)
if p>90 and p<=100:
    print("A")
elif p>80 and p<90:
    print("B")
elif p>60 and p<80:
    print("C")
else:
    print("D")

enter first student marks80
enter second student marks80
enter third student marks80
enter fourth student marks8
enter fivth student marks85
66.6
C


In [19]:
#8
a=45
b=int(input("enter a number"))
if a<b:
    print("a is less than b")
elif b<a:
    print("b is less than a")
else:
    print("error")

enter a number45
error


In [8]:
#9
a=int(input("enter a number till print even number"))
for i in range (2,a+1,2):
    print(i)

enter a number till print even number10
2
4
6
8
10


In [5]:
#10 even number sum
n=int(input("enter number till find sum"))
sum=0
for i in range (0,n+1,2):
    sum=sum+i
    i=i+sum
print(sum)

enter number till find sum20
110


In [7]:
# odd number sum
n=int(input("enter number till find sum"))
sum=0
for i in range (1,n+1,2):
    sum=sum+i
    i=i+sum
print(sum)

enter number till find sum10
25


In [6]:
#10 fibonacci series
n=int(input("enter a number for fibonacci series"))
first_value=0
second_value=1
for i in range (0,n+1):
    if n<=1:
        next=n
    else:
        next=first_value+second_value
        first_value=second_value
        second_value=next
    print(next)

enter a number for fibonacci series10
1
2
3
5
8
13
21
34
55
89
144


In [10]:
# check prime number
a=int(input("enter a number to check prime number"))
limit=int(a/2)+1
for i in range(2,limit):
    b=a%i
    if b%i==0:
        print(a,"is not a prime number")
        break
else:
    (a,"is a prime number")

enter a number to check prime number10
10 is not a prime number


In [17]:
# sum of digits given number
a=9723554
def getsum(a):
    sum=0
    for digit in str(a):
        sum+=int(digit)
    return sum 
print(getsum(a))

35


In [19]:
#revers a number
n=int(input("enter a number"))
a=n
r=0
while n>0:
    d=n%10
    r=r*10+d
    n=n//10
print(r)

enter a number123456
654321


In [9]:
#14 armstrong numbers
lower=int(input("enter a number to start "))
upper=int(input("enter a number to end "))
for num in range (lower,upper+1):
    order = len(str(num))
    sum=0
    power=num
    while power>0:
        digit= power%10
        sum+=digit**power
        power//=10
    if num==sum:
        print(num)

enter a number to start100
enter a number to end2000


In [14]:
# change into binary to decimal
a= input("enter a binary number: ")
def binarytodecimal(a):
    decimal=0
    for i in a:
        decimal=decimal*2+int(i)
    print(decimal)
binarytodecimal(a)

enter a binary number: 10
2


In [24]:
import array
from array import*

In [17]:
array = []
n = int(input("enter elements of array"))
for i in range (0,n):
    l=int(input())
    array.append(l)
print("array =",array)

enter elements of array4
5
6
4
8
array = [5, 6, 4, 8]


In [18]:
array

[5, 6, 4, 8]

In [22]:
# sum of array
def sum (array):
    sum=0
    for i in array:
        sum=sum+i
    print(sum)
sum(array)

23


In [23]:
# sum of two array
arr1=[]
n=int(input("enter the number of elements"))
for i in range(0,n):
    elements=int(input("enter elements of arr1"))
    arr1.append(elements)
print(arr1)

enter the number of elements6
enter elements of arr12
enter elements of arr16
enter elements of arr18
enter elements of arr19
enter elements of arr17
enter elements of arr13
[2, 6, 8, 9, 7, 3]


In [24]:
arr2=[]
n=int(input("enter the number of elements"))
for i in range(0,n):
    elements=int(input("enter elements of arr1"))
    arr2.append(elements)
print(arr2)

enter the number of elements6
enter elements of arr15
enter elements of arr18
enter elements of arr19
enter elements of arr17
enter elements of arr14
enter elements of arr13
[5, 8, 9, 7, 4, 3]


In [26]:
arr1

[2, 6, 8, 9, 7, 3]

In [27]:
arr2

[5, 8, 9, 7, 4, 3]

In [29]:
arr3=arr1+arr2

In [30]:
print(arr3)

[2, 6, 8, 9, 7, 3, 5, 8, 9, 7, 4, 3]


In [31]:
#maximum element
arr3

[2, 6, 8, 9, 7, 3, 5, 8, 9, 7, 4, 3]

In [32]:
max(arr3)

9

In [34]:
min(arr3)

2

In [16]:
# linear search
arr3 = [2,6,8,9,7,3,5,8,9,7,4,3]
def search(arr3):
    for i in range(len(arr3)):
        if arr[i] == 9:
            return i
    return -1
print(i)
search(arr3)

NameError: name 'i' is not defined

In [26]:
# bubble sort in array
arr=array('i',[14,2,53,14,45,16,45,65,48,32,48,95,47,74])
def bubble_sort(arr):
    n=len(arr)
    for i in range (0,n):
        for j in range (0,n-i-1):
            if arr[j]>arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j]
bubble_sort(arr)
print(arr)

array('i', [2, 14, 14, 16, 32, 45, 45, 47, 48, 48, 53, 65, 74, 95])


In [27]:
import numpy as np

In [30]:
# multiply two matrix
a = [[12,7,3],
    [4,5,6],
    [7,8,9]]
b = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]
result = np.dot(a,b)
for i in result:
    print(i)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


In [41]:
#sum of matrix
a = [[12,7,3],
    [4,5,6],
    [7,8,9]]
b = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
result = [[a[i][j]+b[i][j]for j in range(len(a[0]))] for i in range(len(a))]
for r in result:
    print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [46]:
#power of 2
total =  int(input())
for i in range(total):
    print("2 raised to the power ",i,"is",2**i)

3
2 raised to the power  1 is 1
2 raised to the power  2 is 2
2 raised to the power  3 is 4


In [49]:
#number divisible by another number
num=int(input("enter the number jisse divide krna hai"))
div=int(input("enter the number jisko divide krna hai"))
if num%div:
    print("the number is divible")
else:
    print("the number is not divible")

enter the number jisse divide krna hai5
enter the number jisko divide krna hai20
the number is divible


In [2]:
#asc value of character
a=input("enter a character")
result=ord(a)
print(result)

enter a characters
115


In [3]:
# convert decimal to binary,octal,hexadecimal
dec=564
print("the decimal value of ",dec,"is:")
print(bin(dec),"in binary.")
print(oct(dec),"in octal.")
print(hex(dec),"in hexadecimal.")

the decimal value of  564 is:
0b1000110100 in binary.
0o1064 in octal.
0x234 in hexadecimal.


In [10]:
n=int(input('enter a number to print fibbonacci'))
a=1
b=0
c=0
for i in range(0,n):
    c=a+b
    a=b
    b=c
    print(c)

enter a number to print fibbonacci10
1
1
2
3
5
8
13
21
34
55
